email:
  url: "http://103.225.100.138:8080/www/emailservice.php"
  recipients: 'technopunter@googlegroups.com'
  acct-recipient:
    Trader-V2-Alan: alansaviolobo%40gmail.com
    Trader-V2-Pralhad: pro.kamath%40gmail.com
    Trader-V2-Sundar: ssundarganesh%40gmail.com
    Trader-V2-Mahi: mahipraneeth948@gmail.com