email:
  url: "http://trader.technotrix.co.in/www/emailservice.php"
  recipients: 'pro.kamath%40gmail.com%2Calansaviolobo%40gmail.com%2Cssundarganesh%40gmail.com%2Cmahipraneeth948@gmail.com'
  acct-recipient:
    Trader-V2-Alan: alansaviolobo%40gmail.com
    Trader-V2-Pralhad: pro.kamath%40gmail.com
    Trader-V2-Sundar: ssundarganesh%40gmail.com