postgres:
  username: trader
  password:
  host: db-postgresql-blr1-49618-do-user-1003361-0.db.ondigitalocean.com
  port: 25060
  database: trader
  predicate: " WHERE ts= (
    SELECT MAX(ts)
    FROM symbol_data
    where symbol ='{symbol}' and timeframe = {tf}
    ) and symbol ='{symbol}' and timeframe = {tf}"
  symbol_table: public.symbol_data
  summary_table: t_training_result_summary

trading-view:
  username: traderpreethi@gmail.com
  secret: Y.Fcg2hwWu*A

shoonya:
  Trader-V2-Alan:
    user: 'User'
    pwd: 'Password'
    vc: 'User_U'
    apikey: 'API-key'
    imei: 'abc1234'
    token: token
    expiry_date: 2023-01-01
