trade-exec-params:
  push-trade-url: "https://gis.goawrd.gov.in/trade/trade"
  get-trades-url: "https://gis.goawrd.gov.in/trade/trades"
  get-quote-url: "https://gis.goawrd.gov.in/trade/get_quote"
  get-ts-data-url: "https://gis.goawrd.gov.in/trade/get_ts_data"
  email-trades-url: "http://trader.technotrix.co.in/www/dailyreport.php"
  get-orders-url: "https://gis.goawrd.gov.in/trade/orders"
  scrips:
    - scripName: NSE_BPCL
      models:
        - name: trainer.strategies.gspcV2
          direction: BUY
      accounts:
        - name: Trader-V2-Mahi
          quantity-params:
            type: Fixed
            risk: 1
          sendToBroker: True
          sl_factor: 0.02
          tgt_factor: 1.0
    - scripName: NSE_BPCL
      models:
        - name: trainer.strategies.gspcV2
          direction: SELL
      accounts:
        - name: Trader-V2-Mahi
          quantity-params:
            type: Fixed
            risk: 1
          sendToBroker: True
          sl_factor: 0.02
          tgt_factor: 1.0
    - scripName: NSE_BANDHANBNK
      models:
        - name: trainer.strategies.gspcV2
          direction: BUY
      accounts:
        - name: Trader-V2-Mahi
          quantity-params:
            type: Fixed
            risk: 1
          sendToBroker: True
          sl_factor: 0.02
          tgt_factor: 1.0
    - scripName: NSE_BANDHANBNK
      models:
        - name: trainer.strategies.gspcV2
          direction: SELL
      accounts:
        - name: Trader-V2-Mahi
          quantity-params:
            type: Fixed
            risk: 1
          sendToBroker: True
          sl_factor: 0.02
          tgt_factor: 1.0
    - scripName: NSE_WIPRO
      models:
        - name: trainer.strategies.gspcV2
          direction: BUY
      accounts:
        - name: Trader-V2-Mahi
          quantity-params:
            type: Fixed
            risk: 1
          sendToBroker: True
          sl_factor: 0.02
          tgt_factor: 1.0
    - scripName: NSE_WIPRO
      models:
        - name: trainer.strategies.gspcV2
          direction: SELL
      accounts:
        - name: Trader-V2-Mahi
          quantity-params:
            type: Fixed
            risk: 1
          sendToBroker: True
          sl_factor: 0.02
          tgt_factor: 1.0
    - scripName: NSE_ONGC
      models:
        - name: trainer.strategies.rfcV2
          direction: BUY
      accounts:
        - name: Trader-V2-Mahi
          quantity-params:
            type: Fixed
            risk: 1
          sendToBroker: True
          sl_factor: 0.02
          tgt_factor: 1.0
    - scripName: NSE_ONGC
      models:
        - name: trainer.strategies.rfcV2
          direction: SELL
      accounts:
        - name: Trader-V2-Mahi
          quantity-params:
            type: Fixed
            risk: 1
          sendToBroker: True
          sl_factor: 0.02
          tgt_factor: 1.0